import React,{useState}from"react";
import{createRoot}from"react-dom/client";
import{Search,MapPin,CalendarDays,Users,Clock3,ArrowRight,CheckCircle2,Database,Route,SlidersHorizontal}from"lucide-react";
import"./styles.css";
const API=import.meta.env.VITE_API_URL??"http://localhost:8080";
type Place={id:string;name:string;primary_category?:string;secondary_categories:string[];latitude:number;longitude:number;universal_score:number;confidence:number;visit_duration:any};
function App(){const[step,setStep]=useState<"start"|"plan">("start"),[d,setD]=useState(""),[start,setStart]=useState(""),[end,setEnd]=useState(""),[travellers,setTravellers]=useState("2"),[i,setI]=useState("history, food, nature"),[range,setRange]=useState("15"),[loading,setLoading]=useState(false),[error,setError]=useState(""),[result,setResult]=useState<any>(null),[places,setPlaces]=useState<Place[]>([]);
async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setError("");try{const x=await fetch(API+"/api/research/runs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({destination:d,travelStart:start||undefined,travelEnd:end||undefined,travellerCount:Number(travellers),interests:i.split(",").map(x=>x.trim()).filter(Boolean),maxGeographicRangeKm:Number(range)})});const j=await x.json();if(!x.ok)throw Error(j.error??"Research failed");setResult(j);const p=await fetch(API+"/api/research/snapshots/"+j.snapshotId+"/places");setPlaces(p.ok?await p.json():[]);setStep("plan")}catch(e){setError(e instanceof Error?e.message:"Research failed")}finally{setLoading(false)}}
return <main><header><div className="brand"><div className="mark">T</div><div><b>Tripior</b><small>Research Engine</small></div></div><div className="headerLinks"><span>Research</span><span>Knowledge</span><span className="live">● API online</span></div></header>
{step==="start"?<><section className="landing"><div><div className="eyebrow">TRAVEL RESEARCH</div><h1>Research once.<br/><em>Travel better.</em></h1><p className="lead">Tripior builds a reusable, date-aware knowledge base of places and activities before your trip is planned.</p></div><form className="researchCard" onSubmit={submit}><div className="cardTitle"><span>Start a new research</span><small>Tell us about the trip</small></div><label><MapPin size={16}/>Destination<input required value={d} onChange={e=>setD(e.target.value)} placeholder="Kyoto, Japan"/></label><div className="two"><label><CalendarDays size={16}/>Start date<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label><CalendarDays size={16}/>End date<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></div><div className="two"><label><Users size={16}/>Travellers<input type="number" min="1" max="100" value={travellers} onChange={e=>setTravellers(e.target.value)}/></label><label><Route size={16}/>Research range<input type="number" min="2" max="50" value={range} onChange={e=>setRange(e.target.value)}/></label></div><label><SlidersHorizontal size={16}/>Interests<input value={i} onChange={e=>setI(e.target.value)} placeholder="history, food, nature"/></label><button disabled={loading}>{loading?"Building research snapshot…":"Start research"}<ArrowRight size={17}/></button></form></section><section className="principles"><div><Database/><b>Evidence first</b><span>Raw provider data stays separate from canonical Tripior data.</span></div><div><CheckCircle2/><b>Date aware</b><span>Permanent place facts remain separate from temporary conditions.</span></div><div><Route/><b>Reusable output</b><span>Recommendation and itinerary engines consume the snapshot.</span></div></section></>:<Plan result={result} places={places} onBack={()=>setStep("start")}/>}
{error&&<div className="error">{error}</div>}<footer>Tripior · Research Engine · Phase 1</footer></main>}
function Plan({result,places,onBack}:{result:any;places:Place[];onBack:()=>void}){const top=places.slice(0,12);return <section className="plan"><button className="back" onClick={onBack}>← New research</button><div className="planHead"><div><div className="eyebrow">GENERATED RESEARCH PLAN</div><h1>{result.destination.name}</h1><p>{result.destination.country} · {result.coverage.candidateCount} candidates researched</p></div><span className="status"><CheckCircle2 size={15}/> {result.coverage.status}</span></div><div className="summary"><div><CalendarDays/><span>Research snapshot</span><b>{new Date().toLocaleDateString()}</b></div><div><MapPin/><span>Coverage</span><b>{result.coverage.unique} places</b></div><div><Clock3/><span>Pipeline</span><b>{Math.round(result.coverage.durationMs/1000)}s</b></div></div><div className="sectionHead"><div><div className="eyebrow">TRAVEL PLAN TABLE</div><h2>Places ready for recommendation</h2></div><small>Universal research score · confidence</small></div><div className="tableWrap"><table><thead><tr><th>Place</th><th>Category</th><th>Visit</th><th>Quality</th><th>Confidence</th><th></th></tr></thead><tbody>{top.map((p,n)=><tr key={p.id}><td><div className="place"><span>{String(n+1).padStart(2,"0")}</span><b>{p.name}</b></div></td><td>{p.primary_category||p.secondary_categories?.[0]||"Place"}</td><td>{p.visit_duration?.typical_minutes?p.visit_duration.typical_minutes+" min":"Research needed"}</td><td><div className="bar"><i style={{width:Math.round((p.universal_score??0)*100)+"%"}}/></div>{Math.round((p.universal_score??0)*100)}%</td><td>{Math.round((p.confidence??0)*100)}%</td><td><ArrowRight size={16}/></td></tr>)}</tbody></table>{!top.length&&<div className="empty">No canonical places were returned for this snapshot.</div>}</div><div className="notice"><Database size={18}/><div><b>This is the research layer, not the final itinerary.</b><span>The next engine can use these places, dates, constraints and scores to build day-by-day schedules without repeating discovery.</span></div></div></section>}
createRoot(document.getElementById("root")!).render(<App/>);